name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run checks
      run: lein check
    - name: Run unit tests
      run: lein test
    - name: Run integration tests
      run: lein test :integration
